### ISSUE TITLE
Elicitação de Requisitos - Entrevista

### ISSUE THREAD

**Issue by iurisevero** [Requisitos-2019-2-Wire/Wire#15]
## Descrição da Issue
Elicitar requisitos para o aplicativo Wire a partir da técnica de entrevista. A elicitação deverá ser documentada para discussões futuras e para manter uma melhor rastreabilidade do projeto.

### Tasks: 

- [x] Elaborar uma entrevista com relação a comunicação interna de empresas;
- [x] Entrevistar funcionários de empresas corporativas;
- [x] Criar um documento com o resultado das entrevistas

**Comment by iurisevero** [comment]
Tive como ideia para entrevista as seguintes perguntas:
 
* De que modo a empresa onde você trabalha faz backup de dados?
* Qual o meio de comunicação oficial usado para reuniões não presenciais?
* Como é feita a comunicação interna remota da empresa?
* Como é feita a comunicação dos funcionários em caso de pareamento ou outro tipo de trabalho em equipe?
* Os aplicativos utilizados para comunicação são open-source?

Aberto a alterações e sugestões

**Comment by lucasfcm9** [comment]
> Tive como ideia para entrevista as seguintes perguntas:
> 
> * De que modo a empresa onde você trabalha faz backup de dados?
> * Qual o meio de comunicação oficial usado para reuniões não presenciais?
> * Como é feita a comunicação interna remota da empresa?
> * Como é feita a comunicação remota dos funcionários em caso de pareamento ou outro tipo de trabalho em equipe?
> * Os aplicativos utilizados para comunicação são open-source?
> 
> Aberto a alterações e sugestões

Tá show demais, acho essas perguntas muito interessantes. Poderia falar também, durante a entrevista, sobre o Wire e como ele funciona.

**Comment by iurisevero** [comment]
> > Tive como ideia para entrevista as seguintes perguntas:
> > 
> > * De que modo a empresa onde você trabalha faz backup de dados?
> > * Qual o meio de comunicação oficial usado para reuniões não presenciais?
> > * Como é feita a comunicação interna remota da empresa?
> > * Como é feita a comunicação remota dos funcionários em caso de pareamento ou outro tipo de trabalho em equipe?
> > * Os aplicativos utilizados para comunicação são open-source?
> > 
> > Aberto a alterações e sugestões
> 
> Tá show demais, acho essas perguntas muito interessantes. Poderia falar também, durante a entrevista, sobre o Wire e como ele funciona.

É uma boa para tentar ver a reação da pessoa em relação ao app, mas acho que não se encaixa na técnica de análise, já q a ideia e ver como o entrevistado realiza essas ações no cotidiano.
Podemos deixar a informação guardada para uso futuro, caso se encaixe em algo.

**Comment by iurisevero** [comment]
Já foram feitas duas entrevistas para elicitação dos requisitos, segue abaixo o que foi anotado:

#### Entrevistado 1: Sócio e líder técnico na uplug

> * De que modo a empresa onde você trabalha armazena os dados de backup?
> R - Não fazemos backup de arquivos. Comitamos tudo num repositório gigante.
> * Qual o meio de comunicação oficial usado para reuniões não presenciais?
> R - https://meet.jit.si/
> * Como é feita a comunicação interna remota da empresa?
> R - https://meet.jit.si/
> https://telegram.org/
> https://discordapp.com
> * Como é feita a comunicação remota dos funcionários em caso de pareamento ou outro tipo de trabalho em equipe?
> R - https://meet.jit.si/ -> para reunioes que exijam compartilhamento de tela
> https://telegram.org/ -> texto
> https://discordapp.com -> somente audio
> * Os aplicativos utilizados para comunicação são open-source?
> R - https://meet.jit.si/ -> open source
> https://telegram.org/ -> open source
> https://discordapp.com -> proprietário
> * A empresa em que você trabalha mantém e gerencia seu serviço de mensagem ou usa um serviço de mensagens externamente gerenciado?
> R - externamente gerenciado, grátis, open source = telegram
> externamente gerenciado, grátis, open source = jit.si
> externamente gerenciado, grátis, proprietário = discord
> * Você já ouviu falar do Wire?
> R - Não
> *  Veria a possibilidade de mudar as plataformas d comunicação atuais pra uma nova, totalmente open source, multiplataforma e q contém recursos d mensagens, vídeo chamada e armazenamento de arquivos na cloud, com foco em segurança? (tendo opção de self hosted,cloud managed, com plano grátis para poucos usuários, e planos pagos para situações enterprise)
> R - Sim

#### Entrevistado 2: Engenheiro DevOps na AboutYou

> * De que modo a empresa onde você trabalha faz backup de dados?
> R - Tudo fica no Gdrive enterprise
> * Qual o meio de comunicação oficial usado para reuniões não presenciais?
> R - A empresa tem o plano enterprise do google Gsuite, e tem o Hangouts Meet (enterprise) que vem junto.
> https://gsuite.google.com.br/intl/pt-BR/products/meet/
> * Como é feita a comunicação interna remota da empresa?
> R - Hangouts Meet - https://gsuite.google.com.br/intl/pt-BR/products/meet/
> Rocket Chat - https://rocket.chat/
> * Como é feita a comunicação remota dos funcionários em caso de pareamento ou outro tipo de trabalho em equipe?
> R - Hangouts Meet -> video/audio e compartilhamento de tela, code share, etc
> Rocket Chat -> texto
> * Os aplicativos utilizados para comunicação são open-source?
> R - Hangouts Meet -> proprietário
> Rocket Chat -> open source
> * A empresa em que você trabalha mantém e gerencia seu serviço de mensagem ou usa um serviço de mensagens externamente gerenciado?
> R - externamente gerenciado, pago, proprietário = pra video conf e file share
> internamente gerenciado, grátis, opensource = text chat
> * Você já ouviu falar do Wire?
> R - Não.

(para o entrevistado 2, a última pergunta não poderia ser respondida, visto que ele não define essas escolhas)

**Comment by iurisevero** [comment]
> Tive como ideia para entrevista as seguintes perguntas:
> 
> * Qual o meio de comunicação oficial usado para reuniões não presenciais?
> * Como é feita a comunicação interna remota da empresa?
> * Como é feita a comunicação remota dos funcionários em caso de pareamento ou outro tipo de trabalho em equipe?
> * Os aplicativos utilizados para comunicação são open-source?
> 
> Aberto a alterações e sugestões

A pergunta "A empresa em que você trabalha mantém e gerencia seu serviço de mensagem ou usa um serviço de mensagens externamente gerenciado?" foi adicionada à entrevista para que a mesma ficasse mais completa.

**Comment by lucasfcm9** [comment]
Issue realizada!
