### ISSUE TITLE
Adicionar divisões para tabelas.

### ISSUE THREAD

**Issue by caiovfernandes** [Requisitos-2019-2-Wire/Wire#19]
## Descrição da Issue
Adicionar um recurso .css para definir uma linha divisória para as tabelas da wiki.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Desenvolver o .css para adicionar divisões.
- [x] Não sobrescrever tema geral do docsify

### Critérios de aceitação
- [x] Tabelas com divisórias bem definidas.
- [x] Estilização aplicada somente à tabelas, sem alterar visual da wiki.

**Comment by caiovfernandes** [comment]
Divisórias adicionadas sem alterar o tema aplicado ao docsify.
