### ISSUE TITLE
Priorização First Things First.

### ISSUE THREAD

**Issue by caiovfernandes** [Requisitos-2019-2-Wire/Wire#27]
## Descrição da Issue
Desenvolver Priorização do tipo First Things First para os Requisitos Funcionais colhidos até o momento.

### Tasks: 
- [x] Desenvolver FTF.
- [x] Criar uma tela na wiki para a priorização FTF.
- [x] Adicionar a priorização a uma tabela.

### Critérios de aceitação
- [x] Validar com o grupo.
- [x] Validar com o monitor.

**Comment by caiovfernandes** [comment]
Issue finalizada, passou em todos os critérios!
