### ISSUE TITLE
PC1 - Apresentação

### ISSUE THREAD

**Issue by guilherme-mendes** [Requisitos-2019-2-Wire/Wire#5]
## Descrição da Issue
Issue para elaboração da primeira apresentação. 
29/08 - Ponto de Controle 1 - Dinâmica de Grupo: Definição e Planejamento do Projeto, RichPicture.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Definir metodologia, ferramentas, pareamentos, dias e horários das reuniões.
- [x] Elaborar documento com o planejamento do grupo de todo o projeto e imprimi-lo.
- [x] Elaborar slide para apresentação (Sobre o Wire App e porque escolhemos).

**Comment by guilherme-mendes** [comment]
Apresentação e tarefas concluídas.
