### ISSUE TITLE
Implementar tela de metodologia no docsify.

### ISSUE THREAD

**Issue by caiovfernandes** [Requisitos-2019-2-Wire/Wire#7]
## Descrição da Issue
- Implementar tela com as metodologias de interação que o grupo utilizará durante o desenvolvimento da matéria.

### Tasks: 
- [x] Criar .md  com informações sobre nossa metodologia.
- [x] Criar um item na sidebar direcionando à tela de metodologia.

### Critérios de aceitação
- [x] Validar página com o grupo;
- [x] Coerência de informações na página.
